services:
  api-gateway:
    image: ${DOCKER_IMAGE}:IMAGE_TAG_PLACEHOLDER
    container_name: mmb-apigateway
    ports:
      - "${APIGATEWAY_PORT}:${APIGATEWAY_PORT}"   # 외부 8080 -> 내부 8080
    env_file:
      - .env
    networks:
      - mumulbo-network
    restart: no

networks:
  mumulbo-network:
    external: true
    driver: bridge
    name: ${MMB_DOCKER_NETWORK}
