services:
  api-gateway:
    image: ${DOCKER_IMAGE}:IMAGE_TAG_PLACEHOLDER
    container_name: ${APIGATEWAY_NAME}
    ports:
      - "${APIGATEWAY_PORT}:${APIGATEWAY_PORT}"   # 외부 8080 -> 내부 8080
    env_file:
      - .env
    networks:
      - mumulbo-network
    restart: no
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  mumulbo-network:
    external: true
    driver: bridge
    name: ${MMB_DOCKER_NETWORK}
