server:
  port: 8443
  ssl:
    enabled: true
    certificate: /etc/letsencrypt/live/dev.mumulbo.com/fullchain.pem
    certificate-private-key: /etc/letsencrypt/live/dev.mumulbo.com/privkey.pem

spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
    gateway:
      routes:
        #        - id: mmb-question-service
        #          uri: http://question-service:8081     # container name (question-service)
        #          predicates:
        #            - Path=/api/v1/login, /api/v1/login/**
        - id: mmb-grafana
          uri: http://52.78.231.247:3000
          predicates:
            - Path=/grafana, /grafana/**
          filters:
            - RewritePath=/grafana/(?<segment>.*), /${segment}

        - id: mmb-member-service
          uri: http://member-service:8082
          predicates:
            - Host=dev.mumulbo.com
            - Path=/api/v1/member, /api/v1/member/**

        - id: dev-mmb-frontend
          uri: http://frontend-service:80
          predicates:
            - Host=dev.mumulbo.com
            - Path=/, /**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}
