server:
  port: ${APPLICATION_PORT}
  ssl:
    enabled: true
    certificate: /etc/letsencrypt/live/dev.mumulbo.com/fullchain.pem
    certificate-private-key: /etc/letsencrypt/live/dev.mumulbo.com/privkey.pem
  http2:
    enabled: false
    max-http-request-header-size: 65536

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    com.mumulbo.gateway.filter: debug

spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
    gateway:
      preserveHostHeader: false
      routes:
        - id: mmb-grafana
          uri: http://mmb-grafana:3000/login
          predicates:
            - Path=/grafana/**
          filters:
            - RewritePath=/grafana/(?<segment>.*), /${segment}

        - id: mmb-question-service
          uri: http://mmb-question-service:${QUESTION_SERVICE_PORT}     # container name (mmb-question-service)
          predicates:
            - Host=dev.mumulbo.com
            - Path=/api/v1/questions
            - Path=/api/v1/questions/**

        - id: mmb-member-service
          uri: http://mmb-member-service:${MEMBER_SERVICE_PORT}       # container name (mmb-member-service)
          predicates:
            - Host=dev.mumulbo.com
            - Path=/api/v1/members
            - Path=/api/v1/members/**

        - id: mmb-auth-service
          uri: http://mmb-auth-service:${AUTH_SERVICE_PORT}       # container name (mmb-auth-service)
          predicates:
            - Host=dev.mumulbo.com
            - Path=/api/v1/auth/**
            - Path=/api/v1/oauth2/**
            - Path=/login/oauth2/**

        - id: dev-mmb-frontend
          uri: http://mmb-frontend:80
          predicates:
            - Host=dev.mumulbo.com
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}
