server:
  port: ${APIGATEWAY_PORT}
  http2:
    enabled: false
    max-http-request-header-size: 65536
jwt:
  secret: ${JWT_SECRET_KEY}

spring:
  application:
    name: ${APIGATEWAY_NAME}
  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
    gateway:
      preserveHostHeader: false
      routes:
        - id: mmb-grafana
          uri: http://mmb-grafana:${GRAFANA_PORT}/login
          predicates:
            - Path=/grafana/**
          filters:
            - RewritePath=/grafana/(?<segment>.*), /${segment}

        - id: mmb-question-service
          uri: http://mmb-question-service:${QUESTION_SERVICE_PORT}     # container name (mmb-question-service)
          predicates:
            #- Host=${HOST_DOMAIN}
            - Path=/api/v1/questions, /api/v1/questions/**

        - id: mmb-member-service
          uri: http://mmb-member-service:${MEMBER_SERVICE_PORT}       # container name (mmb-member-service)
          predicates:
            #- Host=${HOST_DOMAIN}
            - Path=/api/v1/members, /api/v1/members/**

        - id: mmb-auth-service
          uri: http://mmb-auth-service:${AUTH_SERVICE_PORT}       # container name (mmb-auth-service)
          predicates:
            #- Host=${HOST_DOMAIN}
            - Path=/api/v1/auth/**, /api/v1/oauth2/**, /login/oauth2/**

logging:
  level:
    com.mumulbo.gateway.filter: debug
