server:
  port: ${APIGATEWAY_PORT:8080}
  http2:
    enabled: false
    max-http-request-header-size: 65536
jwt:
  secret: ${JWT_SECRET_KEY:mGIP1HLVfEFZCqnyB+JrVaL1R5UcN15YuMB51MoxKzQ=}

spring:
  application:
    name: ${APIGATEWAY_NAME:mmb-apigateway}
  main:
    web-application-type: reactive
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
    gateway:
      preserveHostHeader: false
      routes:
        - id: mmb-grafana
          uri: http://mmb-grafana:${GRAFANA_PORT:3000}/login
          predicates:
            - Path=/grafana/**
          filters:
            - RewritePath=/grafana/(?<segment>.*), /${segment}

        - id: mmb-question-service
          uri: http://mmb-question-service:${QUESTION_SERVICE_PORT:8083}     # container name (mmb-question-service)
          predicates:
            #- Host=${HOST_DOMAIN}
            - Path=/api/v1/questions, /api/v1/questions/**

        - id: mmb-member-service
          uri: http://mmb-member-service:${MEMBER_SERVICE_PORT:8082}       # container name (mmb-member-service)
          predicates:
            #- Host=${HOST_DOMAIN}
            - Path=/api/v1/members, /api/v1/members/**

        - id: mmb-auth-service
          uri: http://mmb-auth-service:${AUTH_SERVICE_PORT:8081}       # container name (mmb-auth-service)
          predicates:
            #- Host=${HOST_DOMAIN}
            - Path=/api/v1/auth/**, /api/v1/oauth2/**, /login/oauth2/**

        - id: mmb-chat-service
          uri: http://mmb-chat-service:${CHAT_SERVICE_PORT:8084}
          predicates:
            #- Host=${HOST_DOMAIN}
            - Path=/chat/**
          filters:
            - RewritePath=/chat/(?<segment>.*), /chat/${segment}

        - id: mmb-chat-service-ws
          uri: ws://mmb-chat-service:${CHAT_SERVICE_PORT:8084}
          predicates:
            - Path=/ws/chat, /ws/chat/**
          filters:
            - RewritePath=/ws/chat(?<segment>/?.*), /ws/chat${segment}

logging:
  level:
    com.mumulbo.gateway: debug
