server:
  port: 8080
  ssl:
    enabled: false

spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
    gateway:
      routes:
        - id: mmb-grafana
          uri: http://grafana:3000
          predicates:
            - Path=/grafana, /grafana/**
          filters:
            - RewritePath=/grafana/(?<segment>.*), /${segment}

        - id: mmb-question-service
          uri: http://question-service:8081     # container name (question-service)
          predicates:
            - Path=/api/v1/questions, /api/v1/questions/**

        - id: mmb-member-service
          uri: http://member-service:8082       # container name (member-service)
          predicates:
            - Path=/api/v1/members
            - Path=/api/v1/members/**
            - Path=/api/v1/auth/
            - Path=/api/v1/auth/**

        - id: mmb-frontend
          uri: http://mmb-frontend:80
          predicates:
            - Path=/, /**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}
