name: Deploy API Gateway on EC2

on:
  push:
    branches:
      - dev  # dev test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR file
        run: ./gradlew build

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build --no-cache -t "${{ secrets.DOCKER_USERNAME }}/mmb-apigateway:latest" .

      - name: Push Docker image
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/mmb-apigateway:latest"

      - name: Deploy on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/mmb-apigateway:latest
        run: |
          echo "${EC2_KEY}"  > /tmp/hlkim-testkey.pem
          chmod 400 /tmp/hlkim-testkey.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/hlkim-testkey.pem $EC2_USER@$EC2_HOST << EOF
            docker pull $DOCKER_IMAGE
          EOF
#            docker stop api-gateway || true
#            docker rm api-gateway || true
#            docker run -d --name api-gateway -p 80:80 $DOCKER_IMAGE
#          EOF
